---
Name: downloadableproductsconfig
---
SilverStripe\Control\Director:
  rules:
    'downloadproduct': 'SilverCommerce\DownloadableProducts\FileDownloadController'
SilverCommerce\OrdersAdmin\Model\LineItem:
  extensions:
    - SilverCommerce\DownloadableProducts\LineItemExtension
SilverStripe\Assets\File:
  extensions:
    - SilverCommerce\DownloadableProducts\FileExtension