---
Name: downloadableproductsconfig
---
SilverStripe\Control\Director:
  rules:
    'downloadproduct': 'SilverCommerce\DownloadableProducts\Control\DownloadableFileController'
SilverCommerce\OrdersAdmin\Model\LineItem:
  extensions:
    - SilverCommerce\DownloadableProducts\Extensions\LineItemExtension
SilverStripe\Assets\File:
  extensions:
    - SilverCommerce\DownloadableProducts\Extensions\FileExtension