---
Name: downloadableproductsconfig
---
SilverStripe\Control\Director:
  rules:
    'assets/downloadable': 'DownloadableFileController'
SilverCommerce\OrdersAdmin\Model\LineItem:
  extensions:
    - SilverCommerce\DownloadableProducts\LineItemExtension
